language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-users udagram-users
  - docker build -t udagram-feeds udagram-feeds
  - docker tag udagram-users philoniare/udagram-users:latest
  - docker tag udagram-feeds philoniare/udagram-feeds:latest

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push philoniare/udagram-feeds
  - docker push philoniare/udagram-users
