apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-feeds
  labels:
    app: udagram-feeds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-feeds
  template:
    metadata:
      labels:
        app: udagram-feeds
    spec:
      containers:
        - name: udagram-feeds
          image: philoniare/udagram-feeds
          ports:
            - containerPort: 8080
